# Generated by Django 4.1.5 on 2023-02-13 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0028_alter_pledge_pub_date'),
        ('cart', '0002_remove_cart_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('pledgecolorset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.pledgecolorset')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.size')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='cart.CartPledge', to='clothes.pledgecolorset'),
        ),
    ]
