# Generated by Django 4.1.5 on 2023-04-18 14:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0040_remove_pledgecolorsetvisualisation_ip_address_and_more'),
        ('cart', '0003_cartpledge_cart_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccesfulPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2023, 4, 18))),
                ('pledgecolorset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.pledgecolorset')),
            ],
        ),
    ]
