# Generated by Django 4.1 on 2022-08-08 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('slug', models.SlugField(verbose_name='name')),
                ('gender', models.CharField(choices=[('M', 'man'), ('W', 'Woman')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('M', 'man'), ('W', 'Woman')], max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('clothing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothingtype')),
            ],
        ),
    ]
