# Generated by Django 4.1 on 2022-08-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingtype',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
