# Generated by Django 4.1 on 2022-08-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_clothingtype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingtype',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=10),
        ),
    ]
