# Generated by Django 4.1 on 2022-08-08 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_brand_pledge_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.brand'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(default='brand name', max_length=25, unique=True),
        ),
    ]
