# Generated by Django 4.1 on 2022-08-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_pledge_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
