# Generated by Django 4.1 on 2022-08-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0008_alter_pledge_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=10),
        ),
    ]
