# Generated by Django 4.1 on 2022-08-09 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0010_alter_pledge_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 9, 16, 52, 32, 858244, tzinfo=datetime.timezone.utc)),
        ),
    ]
