# Generated by Django 4.1 on 2022-08-10 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0012_alter_pledge_brand_alter_pledge_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 10, 18, 44, 17, 289918, tzinfo=datetime.timezone.utc)),
        ),
    ]
