# Generated by Django 4.1 on 2022-08-10 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0013_alter_pledge_pub_date_alter_pledge_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='slug',
        ),
        migrations.AlterField(
            model_name='pledge',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 10, 15, 35, 16, 258600, tzinfo=datetime.timezone.utc)),
        ),
    ]
