# Generated by Django 4.1.5 on 2023-01-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0013_alter_pledge_pub_date'),
        ('clothes', '0015_alter_pledge_pub_date'),
    ]

    operations = [
    ]
