# Generated by Django 4.1.5 on 2023-01-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0018_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='size',
            field=models.ManyToManyField(to='clothes.size'),
        ),
    ]
