# Generated by Django 4.1.5 on 2023-01-31 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0019_pledge_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='size',
        ),
        migrations.AlterField(
            model_name='pledge',
            name='pub_date',
            field=models.DateField(default=datetime.date(2023, 1, 31)),
        ),
    ]
