# Generated by Django 4.1.5 on 2023-01-31 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0020_color_remove_pledge_size_alter_pledge_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='price',
        ),
        migrations.CreateModel(
            name='PledgeColorSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.color')),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.pledge')),
                ('sizes', models.ManyToManyField(to='clothes.size')),
            ],
        ),
    ]
