# Generated by Django 4.1.5 on 2023-01-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0025_clothingtype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingtype',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
