# Generated by Django 4.1.5 on 2023-02-09 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0026_alter_clothingtype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='pub_date',
            field=models.DateField(default=datetime.date(2023, 2, 9)),
        ),
    ]
