# Generated by Django 4.1.5 on 2023-02-15 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0028_alter_pledge_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='pub_date',
            field=models.DateField(default=datetime.date(2023, 2, 15)),
        ),
    ]
