# Generated by Django 4.1.5 on 2023-02-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0030_alter_pledge_pub_date_alter_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingtype',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
