# Generated by Django 4.1.5 on 2023-02-20 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0032_color_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledgecolorset',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 12, 16, 19, 219106, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='pub_date',
            field=models.DateField(default=datetime.date(2023, 2, 20)),
        ),
    ]
