# Generated by Django 4.1.5 on 2023-02-20 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0033_pledgecolorset_pub_date_alter_pledge_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='pledgecolorset',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 12, 39, 33, 772649, tzinfo=datetime.timezone.utc)),
        ),
    ]
