# Generated by Django 4.1.5 on 2023-04-17 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0038_alter_pledgecolorset_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledgecolorsetvisualisation',
            old_name='ip',
            new_name='ip_address',
        ),
        migrations.AlterField(
            model_name='pledgecolorset',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 15, 2, 11, 905909, tzinfo=datetime.timezone.utc)),
        ),
    ]
