# Generated by Django 4.1.5 on 2023-04-18 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0039_rename_ip_pledgecolorsetvisualisation_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledgecolorsetvisualisation',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='pledgecolorsetvisualisation',
            name='set',
        ),
        migrations.AlterField(
            model_name='pledgecolorset',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 14, 54, 20, 238782, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='IpAddress',
        ),
        migrations.DeleteModel(
            name='PledgeColorSetVisualisation',
        ),
    ]
