# Generated by Django 4.1.5 on 2023-02-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothes', '0029_alter_pledge_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('pledges', models.ManyToManyField(to='clothes.pledge')),
            ],
        ),
    ]
