# Generated by Django 4.1.5 on 2023-04-18 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homeset_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeset',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 14, 54, 20, 250774, tzinfo=datetime.timezone.utc)),
        ),
    ]
